// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package rdb

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (id, office_id, name, password, role)
VALUES ($1, $2, $3, $4, $5)
returning id, office_id, name, password, role, created_at, updated_at
`

type CreateUserParams struct {
	ID       int64    `json:"id"`
	OfficeID int64    `json:"office_id"`
	Name     string   `json:"name"`
	Password string   `json:"password"`
	Role     UserType `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.OfficeID,
		arg.Name,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, office_id, name, password, role, created_at, updated_at from users where id = $1 and office_id = $2
`

type GetUserParams struct {
	ID       int64 `json:"id"`
	OfficeID int64 `json:"office_id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.OfficeID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
